return {
    vr_crosshair_scale = {en = "Crosshair scale (%%)"},
    vr_crosshair_scale_description = {en = "Resize the hand-aim crosshair, charge bars and hit feedback together. Updates while playing. 100%% restores the original size; the default is 70%%."},
    ads_focus = {en = "Aim-down-sights focus"},
    ads_focus_description = {en = "While aiming down sights: a soft vignette at the edges of view, a tighter crosshair and steadier aim. No zoom. Off leaves the view unchanged."},
    vr_aim_stabilization = {en = "Weapon aim stabilisation (%%)"},
    vr_aim_stabilization_description = {en = "Damp small aiming tremors while responding faster to deliberate movement. Higher values steady the aim more. Set to zero to disable. Applies to ranged weapons, including staffs."},
    controller_action_binding_description = {en = "Choose the controller input for this action. Actions can share a control: for example, interact and reload on X. Right-stick left/right actions require turning to be off. Hub overrides apply only in the hub."},
    melee_preview_toggle = {en = "First melee swing preview"},
    melee_preview_toggle_description = {en = "Show or hide the first light attack's direction while holding your melee weapon idle. Starts off each session. This guide does not guarantee a hit."},
    melee_preview_toggle_button = {en = "Toggle preview"},
    scanner_test_keybind = {en = "Device screen check (opens or closes the scanner display on the equipped device)"},
    melee_preview_keybind = {en = "Toggle melee preview shortcut"},
    melee_preview_keybind_description = {en = "Toggle the swing guide without opening chat. Default: F6."},
    vr_gun_pitch = {en = "Aim pitch angle (degrees)"},
    vr_gun_pitch_description = {en = "Tilt aim relative to the controller for every weapon and item, so the crosshair stays put when you switch. Negative angles aim lower; positive angles aim higher. Guns tilt in the hand to match."},
    remote_mission_input = {en = "VR input and hands in online missions"},
    remote_mission_input_description = {en = "On a mission server you do not host, use the same stock-input route as Psykhanium's online rules: controller buttons and movement, hand-aimed firing through the server's normal firing position, and local hand and weapon presentation. Off keeps online missions view-only. Applies immediately."},
    mode_options = {en = "Hub and missions"},
    experimental_options = {en = "Experimental features"},
    -- The sections the options are grouped into (18 September). Each one
    -- answers "what am I trying to change?", so the first screen of the menu
    -- is a short list rather than forty-odd settings in a column.
    -- Titles only: `create_group_template` emits no tooltip, so a group's
    -- description never reaches the player and the title has to carry it
    -- (review, 18 September).
    aiming_options = {en = "Aiming and weapons"},
    body_options = {en = "Your body and hands"},
    world_options = {en = "The world around you"},
    vr_world_scale = {en = "World scale (%%)"},
    vr_world_scale_description = {en = "How big the world feels. Higher makes everything larger and further away; lower makes it smaller and closer. It narrows or widens the distance between your eyes in the game, and your head movement with it. Updates while playing. 100%% is your headset's own measurement."},
    movement_options = {en = "Movement and turning"},
    keyboard_mouse_mode = {en = "Keyboard and mouse in VR"},
    keyboard_mouse_mode_description = {en = "Play with keyboard and mouse. Menus take the mouse cursor and prompts show your keyboard bindings. The mouse moves the reticle inside a deadzone; move further and the view turns with it. Turning your head carries the reticle along. The HUD follows your head as usual. Applies immediately. Without controllers, rename the empty KeyboardMouseOff file in the mod folder to KeyboardMouseOn before launching."},
    keyboard_mouse_mode_switch_on = {en = "Keyboard and mouse in VR (on: KeyboardMouseOn file)"},
    keyboard_mouse_mode_switch_on_description = {en = "A file named KeyboardMouseOn in mods\\darktidevr keeps this mode on, so this toggle cannot turn it off. The file never changes this toggle: rename it back to KeyboardMouseOff with the game closed, and the next launch follows the toggle as it is set here. Disable controllers below still works."},
    keyboard_mouse_disable_controllers = {en = "Disable controllers"},
    keyboard_mouse_disable_controllers_description = {en = "On: the controllers do nothing, in menus or in play, and first-run calibration does not open by itself. Off: the controllers keep working alongside the keyboard and mouse, and both inputs add together."},
    keyboard_mouse_recenter_keybind = {en = "Recentre view"},
    keyboard_mouse_recenter_keybind_description = {en = "Face the direction you are aiming from where you are sitting now, and reset the headset position. Default: Z."},
    keyboard_mouse_horizontal_only = {en = "Horizontal mouselook only"},
    keyboard_mouse_horizontal_only_description = {en = "On: vertical mouse movement moves the aim only to the edge of the deadzone, and you look up and down with your head. Off: moving further also tilts the view up and down, which many players find uncomfortable in VR."},
    keyboard_mouse_aim_style = {en = "Aim style"},
    keyboard_mouse_aim_style_description = {en = "Keyhole: the mouse moves the reticle inside the deadzone, the view turns once it reaches the edge, and turning your head carries the reticle along. Body aim: the mouse always turns the view and the reticle together, and your head looks around freely without moving the reticle. The deadzone applies to Keyhole only; the leash to Body aim only."},
    keyboard_mouse_aim_style_keyhole = {en = "Keyhole"},
    keyboard_mouse_aim_style_body = {en = "Body aim"},
    keyboard_mouse_leash = {en = "Body aim leash (degrees)"},
    keyboard_mouse_leash_description = {en = "Body aim only. How far your head can look away from the reticle before it pulls the reticle along, so it never ends up out of sight. Zero turns the leash off: the reticle stays wherever the mouse put it."},
    keyboard_mouse_deadzone = {en = "Reticle deadzone (degrees)"},
    keyboard_mouse_deadzone_description = {en = "How far the reticle moves away from the centre of your view before the view turns, in every direction. Aiming inside it leaves the view still. Zero turns the view with every mouse movement. Default: 15."},
    spectate_third_person = {en = "Third-person spectating"},
    marker_plane = {en = "World-surface markers"},
    marker_plane_description = {en = "Draw world markers, nameplates and the interaction popup as one surface at the marker's distance, so both eyes see the same thing. Off returns to the per-eye flat markers."},
    vr_full_body_experimental = {en = "Full body (experimental)"},
    vr_full_body_experimental_description = {en = "Show your character's whole body under you: a copy of your character scaled from your calibration, its legs running the game's own animation and its arms solved to your controllers, instead of the tracked hands alone. Takes a few seconds to appear after you turn it on and costs some frames. Its feet follow the animation, not the floor, on slopes and steps."},
    vr_melee_animations = {en = "Melee animations"},
    vr_melee_animations_description = {en = "On: melee attacks play their authored swing, and your hands follow it. Off: your hands and weapon keep tracking your controllers through the whole attack, so you swing it yourself. Hit markers, impacts and slash effects are unaffected either way, and a push and a held block still play their animations, so a shove still reads as a shove and you can see that you are blocking."},
    body_mirror_keybind = {en = "Body mirror shortcut (Psykhanium)"},
    body_mirror_keybind_description = {en = "In the Psykhanium, stands a mirror of your character a few paces ahead, fixed where you summoned it: its head follows your headset, its fingers match yours and your wielded weapon is in its reflected hand, so you can see what others would. Its legs are not mirrored left for right. Press again to remove it. Default: F8."},
    vr_two_hand_support = {en = "Two-hand support"},
    vr_two_hand_support_description = {en = "Grip with your off hand where the weapon's own animation holds the foregrip to steady a gun with both hands. The glove moves onto the foregrip when your hand is close enough to grip. A grip recorded with /dtvr_two_hand_calibrate takes precedence for that weapon this session."},
    vr_two_hand_grip_mode = {en = "Two-hand grip"},
    vr_two_hand_grip_mode_description = {en = "Hold: the gun stays in both hands while you hold grip. Toggle: press grip to take the foregrip and press it again to let go. Either way, once gripped your hands can move any distance apart; bringing them together or crossing them lets go."},
    vr_two_hand_grip_hold = {en = "Hold"},
    vr_two_hand_grip_toggle = {en = "Toggle"},
    vr_virtual_stock = {en = "Virtual stock (experimental)"},
    vr_forearm_holsters = {en = "Weapon hand holsters (experimental)"},
    vr_skull_throw = {en = "Grab and throw the servo skull (experimental)"},
    vr_comms_gesture = {en = "Push to talk with a hand at your mouth (experimental)"},
    vr_weapon_charge_style = {en = "Weapon charge display"},
    vr_weapon_charge_style_count = {en = "Count above the weapon"},
    vr_weapon_charge_style_bars = {en = "The HUD's charge bars above the weapon"},
    vr_weapon_charge_style_off = {en = "Off"},
    vr_item_radial = {en = "Item radial at your hand (experimental)"},
    vr_item_radial_description = {en = "Hold the carried items control and three choices appear at your off hand: your carried item, your stim and your device. Flick the stick towards one and let go to take it. Let go without choosing and the control cycles as it always did, so nothing is lost by turning this on. While the radial is open the stick picks rather than turns you."},
    vr_weapon_charge_style_description = {en = "How a melee weapon's special charges (the force sword, the shock maul, the arc weapons) show at the weapon: a count such as 3/5, the HUD's own charge bars, or nothing. The count also needs Ammo count at the hand on. The HUD panel keeps its copy either way."},
    vr_comms_gesture_description = {en = "Bring your off hand up in front of your mouth and hold it there for half a second to open your microphone, as if speaking into a vox bead; drop the hand to close it. Works alongside the push to talk binding, not instead of it, and never while that hand is on the gun."},
    vr_skull_throw_description = {en = "With the flamethrower servo skull talented, the skull hovers in view at your off-hand side. Grip it with your off hand and it locks to your palm and turns with your hand; mark a target and let go with a throw: it leaves your hand on your own arc, whichever way you threw, then turns for the target. Thrown away from the target, it arrives a moment after the attack begins."},
    vr_forearm_holsters_description = {en = "Small holsters in a line above your gun hand's forearm, from the wrist: your other weapon, stim, carried item and device. Reach in with your other hand and press grip to equip. A small model of each item is always shown there; the one your hand is in grows and ticks (with Holster labels on, its name shows above it), the weapon shows its ammo or charges beneath it, and they hide while you two-hand the gun or aim down its sights."},
    vr_ads_zoom = {en = "Aim zoom (%%)"},
    vr_ads_zoom_description = {en = "How much closer the world looks while you aim down the sights, as a percentage. The zoom eases in with the aim and out again; 0 turns it off. It needs Aim focus on. Keep it small: the world gets larger, not sharper."},
    vr_wrist_display = {en = "Wrist display"},
    vr_wrist_display_scale = {en = "Wrist display size (%%)"},
    vr_sway_cancel = {en = "Cancel weapon sway (%%)"},
    vr_sway_cancel_description = {en = "Removes the game's artificial weapon sway from your shots, so only your own hands' steadiness counts. 100%% removes it; 0%% (the default) keeps the stock sway. Recoil and spread are unchanged. Applies wherever hand aim drives the game."},
    vr_wrist_display_scale_description = {en = "Resize the wrist display's bars and numbers. Updates while playing."},
    vr_wrist_display_description = {en = "Health, toughness and stamina bars with their numbers, always shown in your off-hand glove's cuff and drawn in front of everything. Not in the hub."},
    vr_teammate_status = {en = "Teammate status above teammates"},
    vr_teammate_status_description = {en = "Each teammate's name, toughness and health bars float above their head, in front of everything and at a readable size at any distance, with DOWNED, NETTED and similar when they need help. Their panels in the team HUD are hidden while this is on; yours stays."},
    vr_holster_counts = {en = "Holster labels"},
    vr_holster_counts_description = {en = "With Weapon hand holsters on, the item your hand is in shows its name above it."},
    vr_sight_ads = {en = "Aim down sights by raising the gun (experimental)"},
    vr_sight_ads_description = {en = "Bringing a gun's sights up to your eye aims down the sights, and lowering it stops. Your aim button still works too. Only for guns that aim down sights, and only once the gun's sight height is known (the galvanic rifle now; other guns after aiming down their sights once)."},
    vr_virtual_stock_description = {en = "While you hold a rifle in both hands, bringing its butt to your shoulder rests it there: the gun then aims from your shoulder to your front hand, so small movements of the gun hand no longer swing it. The shoulder is estimated from your headset and hands."},
    vr_haptics_mode = {en = "Controller vibration"},
    vr_haptics_mode_description = {en = "Informative: vibrations that tell you something, such as your hand reaching a gun's foregrip or an armed holster, the grip taking hold, the clip running dry, a reload finishing and ammo running low. Immersive: the feel of your actions, such as every shot, along with the most important of those notices."},
    vr_haptics_strength = {en = "Controller vibration strength (percent)"},
    vr_haptics_strength_description = {en = "Scales every vibration. Above 100 strengthens the light ones; the strongest are already at the controller's limit."},
    vr_haptics_off = {en = "Off"},
    vr_haptics_informative = {en = "Informative"},
    vr_haptics_immersive = {en = "Immersive"},
    vr_ammo_readout = {en = "Ammo count at the hand"},
    vr_ammo_readout_description = {en = "Show the ranged weapon's clip and reserve (or heat) beside your weapon hand instead of on the HUD panel. With a melee weapon that has special charges (such as the Skitarius arc maul, two-handed force swords, some axes, crowbars and shivs), its charges."},
    hud_visible = {en = "Show the HUD panel"},
    hud_visible_description = {en = "Off hides the fixed HUD panel (health, ammo, objectives, prompts). World markers and the crosshair stay."},
    spectate_third_person_description = {en = "When dead or captured and watching a teammate, follow them with the third-person camera instead of looking through their eyes. Applies on the next mission."},
    hub_third_person = {en = "Third-person body in the hub"},
    hub_third_person_description = {en = "Show the stock third-person character in the hub instead of the first-person body, with the equipped weapons hidden. Combat areas always use first person. Applies on the next hub visit."},
    stereo_cinematics = {en = "In-engine cinematics in stereo"},
    stereo_cinematics_description = {en = "Watch in-engine cutscenes in the world: the cinematic camera moves and turns you, your head adds its own look, and subtitles are shown on the HUD panel. Off shows cutscenes on the flat panel. Cinematic cameras cut and shake; turn this off if that is uncomfortable."},
    psykhanium_online_rules = {en = "Online combat rules in Psykhanium"},
    psykhanium_online_rules_description = {en = "Aim with the right hand using normal firing positions, button melee and movement rules. Room movement stays visual and training aids remain. Applies on your next visit to Psykhanium; online missions are still under development."},
    vr_menu_back = {en = "B"},
    vr_menu_hold_skip = {en = "Hold RT"},
    vr_menu_point_select = {en = "Point + RT"},
    vr_menu_point_secondary = {en = "Point + LT"},
    vr_turning = {en = "VR turning"},
    vr_turning_description = {en = "Turn with the right stick horizontally. Centre it after menus, tracking loss or changing modes. Keyboard and mouse controls remain available."},
    vr_turn_mode = {en = "Turning mode"},
    vr_turn_mode_description = {en = "Smooth turning is the default. Snap turns once per stick deflection. Turn this off to use left/right stick shortcuts instead."},
    vr_turn_smooth = {en = "Smooth"},
    vr_turn_snap45 = {en = "Snap 45 degrees"},
    vr_turn_snap90 = {en = "Snap 90 degrees"},
    vr_turn_off = {en = "Off (allow horizontal shortcuts)"},
    vr_turn_speed = {en = "Smooth speed (degrees per second)"},
    vr_turn_speed_description = {en = "Speed at full right-stick deflection. Partial deflection turns more slowly. Only applies to smooth turning."},
    vr_prompt_right_trigger = {en = "RT"},
    vr_prompt_left_trigger = {en = "LT"},
    vr_prompt_right_grip = {en = "R Grip"},
    vr_prompt_left_grip = {en = "L Grip"},
    vr_prompt_x = {en = "X"},
    vr_prompt_y = {en = "Y"},
    vr_prompt_a = {en = "A"},
    vr_prompt_b = {en = "B"},
    vr_prompt_l3 = {en = "L3"},
    vr_prompt_r3 = {en = "R3"},
    vr_prompt_menu = {en = "Menu"},
    vr_prompt_right_stick_up = {en = "RS Up"},
    vr_prompt_right_stick_down = {en = "RS Down"},
    vr_prompt_right_stick_left = {en = "RS Left"},
    vr_prompt_right_stick_right = {en = "RS Right"},
    vr_prompt_switch = {en = "switch"},
    controller_bindings = {en = "Combat controller bindings"},
    controller_hub_bindings = {en = "Hub overrides"},
    controller_hub_bindings_description = {en = "Choose a different control for an action in the hub, or use Same as combat. Release held controls after changing context."},
    vr_action_inherit = {en = "Same as combat"},
    controller_grip_bindings = {en = "While gripping"},
    controller_grip_bindings_description = {en = "Different controls while your off hand holds a gun's foregrip with Two-hand support. Same as combat keeps the normal control. A button already held when you take or leave the grip keeps its action until you let go."},
    vr_action_inventory = {en = "Open inventory / talents"},
    vr_action_pocketable = {en = "Equip carried item / supply crate"},
    vr_action_stim = {en = "Equip stim"},
    vr_action_device = {en = "Equip scanner / mission device"},
    vr_action_cycle_pocketables = {en = "Cycle carried item / stim"},
    vr_action_inspect_target = {en = "Inspect operative / pet companion"},
    vr_action_tactical_overlay = {en = "Hold tactical overlay"},
    vr_action_communication_wheel = {en = "Hold communication wheel"},
    vr_action_push_to_talk = {en = "Hold push-to-talk"},
    vr_hub_bind_right_trigger = {en = "Hub: right trigger"},
    vr_hub_bind_left_trigger = {en = "Hub: left trigger"},
    vr_hub_bind_right_grip = {en = "Hub: right grip"},
    vr_hub_bind_left_grip = {en = "Hub: left grip"},
    vr_hub_bind_x = {en = "Hub: X"},
    vr_hub_bind_y = {en = "Hub: Y"},
    vr_hub_bind_a = {en = "Hub: A"},
    vr_hub_bind_b = {en = "Hub: B"},
    vr_hub_bind_l3 = {en = "Hub: L3"},
    vr_hub_bind_r3 = {en = "Hub: R3"},
    vr_hub_bind_menu = {en = "Hub: menu button"},
    vr_hub_bind_right_stick_up = {en = "Hub: right stick up"},
    vr_hub_bind_right_stick_down = {en = "Hub: right stick down"},
    vr_hub_bind_right_stick_left = {en = "Hub: right stick left (turning off)"},
    vr_hub_bind_right_stick_right = {en = "Hub: right stick right (turning off)"},
    controller_bindings_description = {en = "Choose a control beside each action. Unbound actions have no controller input. Actions may share a button; saved extra bindings are preserved until you replace them. Release buttons and centre the stick after changes. Menu navigation keeps its standard controls. Reset settings to restore the original layout."},
    vr_bind_right_trigger = {en = "Right trigger"},
    vr_bind_left_trigger = {en = "Left trigger"},
    vr_bind_right_grip = {en = "Right grip"},
    vr_bind_left_grip = {en = "Left grip"},
    vr_bind_x = {en = "X (left primary button)"},
    vr_bind_y = {en = "Y (left secondary button)"},
    vr_bind_a = {en = "A (right primary button)"},
    vr_bind_b = {en = "B (right secondary button)"},
    vr_bind_l3 = {en = "L3 (left stick click)"},
    vr_bind_r3 = {en = "R3 (right stick click)"},
    vr_bind_menu = {en = "Left menu button"},
    vr_bind_right_stick_up = {en = "Right stick up"},
    vr_bind_right_stick_down = {en = "Right stick down"},
    vr_bind_right_stick_left = {en = "Right stick left (turning off)"},
    vr_bind_right_stick_right = {en = "Right stick right (turning off)"},
    vr_action_unbound = {en = "Unbound"},
    vr_action_primary = {en = "Primary attack / fire"},
    vr_action_alternate = {en = "Aim / block / alternate attack"},
    vr_action_special = {en = "Weapon special"},
    vr_action_interact = {en = "Interact"},
    vr_action_reload = {en = "Reload"},
    vr_action_interact_reload = {en = "Interact + reload (original)"},
    vr_action_pocketable_device = {en = "Carried item + scanner (original)"},
    vr_action_quick_wield = {en = "Switch weapon"},
    vr_action_jump = {en = "Jump"},
    vr_action_dodge = {en = "Dodge"},
    vr_action_jump_dodge = {en = "Jump + dodge (original)"},
    vr_action_crouch = {en = "Crouch"},
    vr_action_sprint = {en = "Sprint"},
    vr_action_tag = {en = "Tag target"},
    vr_action_blitz = {en = "Blitz / grenade"},
    vr_action_combat_ability = {en = "Combat ability"},
    vr_action_inspect = {en = "Inspect weapon"},
    vr_action_menu = {en = "Open pause menu"},
    hud_editor = {en = "HUD layout editor"},
    hud_editor_button = {en = "Toggle editor"},
    hud_editor_description = {en = "Requires the separate Custom HUD mod. Select this, then close the menus to edit in the desktop view. Select again before closing to cancel."},
    hud_editor_dependency = {en = "Install and enable Custom HUD to edit the HUD layout."},
    hud_editor_gameplay = {en = "Enter gameplay with the VR HUD enabled before opening its layout editor."},
    hud_editor_close_menu = {en = "Close the menus to toggle HUD layout editing in the desktop view."},
    hud_editor_cancelled = {en = "HUD layout editor request cancelled."},
    hud_editor_notice = {en = "Use the desktop view to edit your HUD layout."},
    hud_focus_notice = {en = "Game window not focused: click the Darktide window on the desktop (frame generation and controls pause)."},
    focus_warning = {en = "Warn when the game window loses focus"},
    focus_warning_description = {en = "Show a notice on the VR HUD while another window has the desktop focus. Frame generation and controller input stop until the Darktide window is focused again."},
    hud_options = {en = "HUD"},
    hud_size = {en = "HUD size (%%)"},
    hud_size_description = {
        en = "Scale the whole HUD panel. The default value uses the standard VR layout. Applies immediately when the VR HUD is active.",
    },
    hud_distance = {en = "HUD distance (m)"},
    hud_distance_description = {
        en = "Move the HUD nearer or farther while keeping approximately the same apparent size. Applies immediately when the VR HUD is active.",
    },
    hud_internal_scale = {en = "HUD text and icon size (%%)"},
    hud_internal_scale_description = {
        en = "Scale objects inside the HUD without enlarging the panel. Large values may require layout adjustments. Saved item positions are preserved.",
    },
    mod_name = {
        en = "Darktide VR",
    },
    mod_description = {
        en = "Experimental native stereo VR support for Darktide.",
    },
    movement_reference = {
        en = "Movement direction",
    },
    movement_reference_head = {
        en = "Headset-relative",
    },
    -- The stored value is still "left_hand". The label names the hand (user,
    -- 16 September); when a handedness setting exists it reads "Right-hand"
    -- for a left-handed player, since the code behind it names the off hand.
    movement_reference_left_hand = {
        en = "Left-hand-relative",
    },
}
